export const STATE_KEY: 'movies' = 'movies';

export enum MoviesActionType {
  RETRIEVE_SEARCH_SECTION_MOVIES = 'movies/RETRIEVE_SEARCH_SECTION_MOVIES',
  STORE_TOP_RATED_MOVIES = 'movies/STORE_TOP_RATED_MOVIES',
  STORE_MOVIES_BY_GENRE = 'movies/STORE_MOVIES_BY_GENRE',
  STORE_RECOMMENDED_MOVIES = 'movies/STORE_RECOMMENDED_MOVIES',
  RETRIEVE_MOVIES_FAILURE = 'movies/RETRIEVE_MOVIES_FAILURE',
}
